apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: cld-streaming
data:
  kafka-metrics-config.yaml: |
    lowercaseOutputName: true
    rules:
    # This rule extracts the 'topic' and 'name' into proper labels
    - pattern: "kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|Value)"
      name: "kafka_server_$1_$2"
      labels:
        topic: "$3"
    # Keep the catch-all at the bottom so you don't lose other metrics
    - pattern: ".*"