apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: cld-streaming # Ensure this matches your Kafka namespace
  labels:
    app: strimzi
data:
  kafka-metrics-config.yaml: |
    lowercaseOutputName: true
    rules:
      - pattern: ".*"
      #- pattern: "kafka.server<type=(.+), name=(.+)><>(Count|Value)"
      #  name: "kafka_server_$1_$2"
      #- pattern: "kafka.controller<type=(.+), name=(.+)><>(Count|Value)"
      #  name: "kafka_controller_$1_$2"
      #- pattern: "kafka.network<type=(.+), name=(.+)><>(Count|Value)"
      #  name: "kafka_network_$1_$2"
